### ISSUE TITLE
object.properties for an ITEM export seems to remote last character of otherIds

### ISSUE THREAD

**Issue by revgum** [DSpace/dspace-replicate#17]
We found that exporting an ITEM is reliably generating `otherIds` with an additional missing character. 

> bagType AIP
> objectType item
> objectId 1957/59277
> ownerId 1957/4
> otherIds 1957/4390

otherIds should be **1957/43909** in this case.

I'm supposing that the following line is taking one too many characters:
`fwriter.writeProperty(OTHER_IDS, linkedStr.substring(0, linkedStr.length() - 2));`

should probably be

`fwriter.writeProperty(OTHER_IDS, linkedStr.substring(0, linkedStr.length() - 1));`

**Comment by tdonohue** [comment]
Fixed by #18
