### ISSUE TITLE
RTS version 7.0 only supports DSpace 7.0, and not 7.1

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-replicate#66]
While releasing [RTS version 7.0](https://github.com/DSpace/dspace-replicate/releases/tag/dspace-replicate-7.0), I discovered that it won't compile if I try to use it with DSpace 7.1 (or later).  Therefore RTS 7.0 is only compatible with DSpace 7.0.

Here's the compilation issues: https://github.com/DSpace/dspace-replicate/runs/4241502698?check_suite_focus=true

Here's the change I made to get it to support DSpace 7.1 or later: https://github.com/DSpace/dspace-replicate/commit/6c1dd04999ef2bacf113cc699029294a59b4588f (the change is the one to the `dspace.version` tag)

**Comment by bbranan** [comment]
This issue is resolved by PR https://github.com/DSpace/dspace-replicate/pull/67

**Comment by tdonohue** [comment]
Closing, fixed in #67
